MorningStarSupply/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MorningStarSupply.Context;
using MorningStarSupply.Services;
using MStarSupply.Models;
using System.Diagnostics;

namespace MStarSupply.Controllers
{
    public class HomeController : Controller
    {
        private readonly GraficoService _grafico;

        public HomeController(GraficoService grafico)
        {
            _grafico = grafico ?? throw new ArgumentNullException(nameof(grafico));
        }


        public IActionResult Index()
        {
            var mes = new List<string>();
            var quantidade = new List<int>();
            

            var mesSaida = new List<string>();
            var quantidadeSaida = new List<int>();

            var entradas = _grafico.GetQuantidadeMensalEntrada();
            var saidas = _grafico.GetQuantidadeMensalSaida();

            foreach (var n in entradas)
            {
                quantidade.Add(n.QuantidadeMercadoria);
                mes.Add(n.Mes);
                
            }

            ViewBag.QuantidadeEnt = quantidade;
            ViewBag.MesEnt = mes;
            

            foreach (var n in saidas)
            {
                quantidadeSaida.Add(n.QuantidadeMercadoria);
                mesSaida.Add(n.Mes);
               
            }

            ViewBag.QuantidadeSai = quantidadeSaida;
            ViewBag.MesSai = mesSaida;
            


            return View();
        }



        
    }
}

MorningStarSupply/Controllers/MercadoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MorningStarSupply.Models;
using MorningStarSupply.Repositories;
using MorningStarSupply.Repositories.Interfaces;

namespace MorningStarSupply.Controllers
{
    public class MercadoriaController : Controller
    {
        private readonly IMercadoriaRepository _repository;

        public MercadoriaController(IMercadoriaRepository repository)
        {
            _repository = repository;
        }

        public IActionResult List()
        {
            var listaMercadorias = _repository.Mercadorias;
            return View(listaMercadorias);
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            
                return NotFound();
            

            var mercadoria = await _repository.FindByIdAsync(id);

            if (mercadoria == null)
                return NotFound();

            return View(mercadoria);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Mercadoria mercadoria)
        {
            if(id != mercadoria.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _repository.Update(mercadoria);
            }

            return RedirectToAction("List");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)

                return NotFound();


            var mercadoria = await _repository.FindByIdAsync(id);

            if (mercadoria == null)
                return NotFound();

            return View(mercadoria);
        }

        [HttpPost,ActionName("Delete")] 
        public async Task<IActionResult> Delete(int id)
        {
   
            var mercadoria = await _repository.FindByIdAsync(id);
            await _repository.Delete(mercadoria);


            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Create(Mercadoria novaMercadoria)
        {
            //valida?
            if (ModelState.IsValid)
            {
                

                //existe igual?
                var igual = _repository.Mercadorias.FirstOrDefault(m => m.NumeroRegistro == novaMercadoria.NumeroRegistro);
                if (igual != null)
                
                    return RedirectToAction("Create");

                _repository.AddToMercadorias(novaMercadoria);
                return RedirectToAction("Create");
            }
            else
            {
                return View(novaMercadoria);
            }
        }

      
    }
}

MorningStarSupply/Views/Home/Index.cshtml
@{

    var quant = ViewBag.QuantidadeEnt;
    var mesEnt = ViewBag.MesEnt;

    var mesSai = ViewBag.MesSai;
    var quantSai = ViewBag.QuantidadeSai;

    var mesEntSerializado = Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(mesEnt));
    var quantEntSerializado = Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(quant));

    var mesSaiSerializado = Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(mesSai));
    var quantSaiSerializado = Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(quantSai));
}

  <div id="preview" class="preview">
      <div style="display: none;"></div>
          <div>
              <div data-draggable="true" style="position: relative;">
                  <!----><!---->
                  <section draggable="false" class="overflow-hidden pt-0" data-v-271253ee="">
                      <section class="mb-10"> 
                          <!-- Background image -->
                    <div class="p-5 text-center bg-image" style=" background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg'); height: 500px; background-size: cover; background-position: 50% 50%; background-color: rgb(255, 255, 255);" aria-controls="#picker-editor">
                    </div> 
                              <!-- Background image -->
                              <div class="container"> 
                                  <div class="card mx-4 mx-md-5 text-center shadow-5-strong" style=" margin-top: -200px; background: hsla(0, 0%, 100%, 0.7); backdrop-filter: blur(30px); "> 
                                      <div class="card-body px-4 py-5 px-md-5">
                                            <h1 class="display-3 fw-bold ls-tight mb-4">  
                                                <span>Gerencie seu estoque com a</span>
                                                <br> <span style="color:#20235a;">Morning Star</span> 
                                            </h1>
                                            <a asp-area=""  asp-action="Create" asp-controller="Mercadoria" 
                                            class="btn btn-lg py-3 px-5 mb-2 mb-md-0 me-md-2" role="button"
                                            style="color:white; background-color:#20235a">
                                                Cadastrar
                                            </a>
                                        
                                      </div>
                                  </div> 
                              </div> 
                      </section>
                   </section><!---->
               </div>
          
          </div>
    <div class="row align-content-center m-5">
        <div class="col-md-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold" style="color:#20235a;">Gráfico de Entradas</h6>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="pt-4 pb-2">
                        <canvas id="Entrada"></canvas>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold" style="color:#20235a;">Gráfico de Saídas</h6>

                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="pt-4 pb-2">
                        <canvas id="GraficoSaida"></canvas>
                    </div>

                </div>
            </div>
        </div>

    </div>

</div>

  

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var mesSai = @mesSaiSerializado;
    var quantSai = @quantSaiSerializado;
    const ctx = document.getElementById('GraficoSaida');

    new Chart(ctx, {
        type: 'pie',
        data: {
            labels: mesSai,
            datasets: [{
                label: 'Quantidade de Saídas',
                data: quantSai,
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
        }
    });

    var reg = @mesEntSerializado;
    var quant = @quantEntSerializado;
    const ctxSai = document.getElementById('Entrada');

    new Chart(ctxSai, {
        type: 'pie',
        data: {
            labels: reg,
            datasets: [{
                label: 'Quantidade de Entradas',
                data: quant,
                borderWidth: 1
                

            }]
        },
        options: {
            responsive: true,
        }
    });
</script>