MorningStarSupply/Controllers/EntradaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MorningStarSupply.Models;
using MorningStarSupply.Repositories.Interfaces;

using System.Security.Cryptography;

namespace MorningStarSupply.Controllers
{
    public class EntradaController : Controller
    {
        private readonly IEntradaRepository repository;
        private readonly IWebHostEnvironment _webHostEnv;

   

        public EntradaController(IEntradaRepository repository, IWebHostEnvironment webHostEnv)
        {
            this.repository = repository;
            _webHostEnv = webHostEnv;
        }

        public IActionResult List()
        {
            var listaEntradas = repository.Entradas;
            return View(listaEntradas);
        }

        public IActionResult Create()
        {
            ViewBag.Mercadorias = repository.GetListMercadorias().Select(c => new SelectListItem()
            { Text = c.Nome, Value = c.NumeroRegistro.ToString() }).ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Entrada novaEntrada)
        {
            //valida?

            if (ModelState.IsValid)
            {
                
                repository.AddToEntradas(novaEntrada);
                return RedirectToAction("Create");


            }
            else

                return RedirectToAction("Create");



        }

        public async Task<IActionResult> Edit(int? id)
        {
            

            if (id == null)

                return NotFound();
            var mercadoria = await repository.FindByIdAsync(id);

            if (mercadoria == null)
                return NotFound();

            ViewBag.Mercadorias = repository.GetListMercadorias().Select(c => new SelectListItem()
            { Text = c.Nome, Value = c.NumeroRegistro.ToString() }).ToList();

            return View(mercadoria);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Entrada entrada)
        {
            if (id != entrada.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await repository.Update(entrada);
            }

            return RedirectToAction("List");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)

                return NotFound();
            var entrada = await repository.FindByIdAsync(id);

            if (entrada == null)
                return NotFound();

            return View(entrada);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {

            var entrada = await repository.FindByIdAsync(id);
            await repository.Delete(entrada);


            return RedirectToAction("List");
        }


    }
}

MorningStarSupply/Controllers/GraficoController.cs
using Microsoft.AspNetCore.Mvc;
using MorningStarSupply.Models;
using MorningStarSupply.Services;

namespace MorningStarSupply.Controllers
{
    public class GraficoController : Controller
    {
        private readonly GraficoService _grafico;

        public GraficoController(GraficoService grafico)
        {
            _grafico = grafico ?? throw new ArgumentNullException(nameof(grafico));
        }




        [HttpGet]
        public IActionResult Index()
        {
            var mes = new List<string>();
            var quantidade = new List<int>();
            int totalEntrada = 0;

            var mesSaida = new List<string>();
            var quantidadeSaida = new List<int>();
            int totalSaida = 0;


            var entradas = _grafico.GetQuantidadeMensalEntrada();
            var saidas = _grafico.GetQuantidadeMensalSaida();

            foreach (var n in entradas)
            {
                quantidade.Add(n.QuantidadeMercadoria);
                mes.Add(n.Mes);
                totalEntrada += n.QuantidadeMercadoria;
            }

            ViewBag.QuantidadeEnt = quantidade;
            ViewBag.MesEnt = mes;
            ViewBag.TotalE = totalEntrada;

            foreach (var n in saidas)
            {
                quantidadeSaida.Add(n.QuantidadeMercadoria);
                mesSaida.Add(n.Mes);
                totalSaida += n.QuantidadeMercadoria;
            }

            ViewBag.QuantidadeSai = quantidadeSaida;
            ViewBag.MesSai = mesSaida;
            ViewBag.TotalS = totalSaida;


            return View();
        }
    }
}

MorningStarSupply/Controllers/RelatorioController.cs
using FastReport.Export.PdfSimple;
using Microsoft.AspNetCore.Mvc;
using MorningStarSupply.Services;

namespace MorningStarSupply.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly RelatorioService service;
        private readonly IWebHostEnvironment _webHostEnv;

        public RelatorioController(RelatorioService service, IWebHostEnvironment webHostEnv)
        {
            this.service = service;
            _webHostEnv = webHostEnv;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RelatorioEntrada(DateTime? minDate, DateTime? maxDate)
        {
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }


            var caminhoReport = Path.Combine(_webHostEnv.WebRootPath, @"reports\ReportMvc.frx");
            var reportFile = caminhoReport;
            var freport = new FastReport.Report();
            var entradas = await service.FindByDateAsync(minDate, maxDate);

            freport.Report.Load(reportFile);
            freport.Dictionary.RegisterBusinessObject(entradas, "ListaEntradas", 10, true);
            //freport.Report.Save(reportFile);
            freport.Prepare();

            var pdfExport = new PDFSimpleExport();

            using MemoryStream ms = new MemoryStream();
            pdfExport.Export(freport, ms);
            ms.Flush();

            return File(ms.ToArray(), "application/pdf");



        }

        public async Task<IActionResult> RelatorioSaida(DateTime? minDate, DateTime? maxDate)
        {
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }



            var caminhoReport = Path.Combine(_webHostEnv.WebRootPath, @"reports\ReportMvc.frx");
            var reportFile = caminhoReport;
            var freport = new FastReport.Report();
            var saidas = await service.FindSaidasByDateAsync(minDate, maxDate);

            freport.Report.Load(reportFile);
            freport.Dictionary.RegisterBusinessObject(saidas, "ListaEntradas", 10, true);
            //freport.Report.Save(reportFile);
            freport.Prepare();

            var pdfExport = new PDFSimpleExport();

            using MemoryStream ms = new MemoryStream();
            pdfExport.Export(freport, ms);
            ms.Flush();

            return File(ms.ToArray(), "application/pdf");


        }
    }
}

MorningStarSupply/Controllers/SaidaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MorningStarSupply.Models;
using MorningStarSupply.Repositories.Interfaces;

namespace MorningStarSupply.Controllers
{
    public class SaidaController : Controller
    {
        private readonly ISaidaRepository repository;

        public SaidaController(ISaidaRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult List()
        {
            var listaSaidas = repository.Saidas;
            return View(listaSaidas);
        }

        public IActionResult Create()
        {
            ViewBag.Mercadorias = repository.GetListMercadorias().Select(c => new SelectListItem()
            { Text = c.Nome, Value = c.NumeroRegistro.ToString() }).ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Saida novaSaida)
        {
            //valida?

            if (ModelState.IsValid)
            {

                repository.AddToSaidas(novaSaida);
                return RedirectToAction("Create");


            }
            else

                return RedirectToAction("Create");



        }

        public async Task<IActionResult> Edit(int? id)
        {


            if (id == null)

                return NotFound();
            var mercadoria = await repository.FindByIdAsync(id);

            if (mercadoria == null)
                return NotFound();

            ViewBag.Mercadorias = repository.GetListMercadorias().Select(c => new SelectListItem()
            { Text = c.Nome, Value = c.NumeroRegistro.ToString() }).ToList();

            return View(mercadoria);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Saida saida)
        {
            if (id != saida.Id)
                return NotFound();

            if (ModelState.IsValid)
            
                await repository.Update(saida);
            

            return RedirectToAction("List");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)

                return NotFound();
            var saida = await repository.FindByIdAsync(id);

            if (saida == null)
                return NotFound();

            return View(saida);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {

            var saida = await repository.FindByIdAsync(id);
            await repository.Delete(saida);


            return RedirectToAction("List");
        }


    }
}

MorningStarSupply/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MStar_Supply</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MStar_Supply.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

</head>
<body>

    <nav class="sb-topnav navbar navbar-expand" style="background-color:#20235a">
            <!-- Navbar Brand-->
            <img class="m-2" src="~/img/mstarsupply.png"/>
            
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            </div>
            <!-- Navbar-->
            
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            
                            <a class="nav-link" asp-area=""  asp-action="Index" asp-controller="Home" >
                                <div class="sb-nav-link-icon"><i class="fas fa-house"></i></div>
                                Home
                            </a>
                            <div class="sb-sidenav-menu-heading">Gerenciamento</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Cadastro
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="Mercadoria" asp-action="Create">Mercadorias</a>
                                <a class="nav-link" asp-area="" asp-controller="Entrada" asp-action="Create">Entradas</a>
                                <a class="nav-link" asp-area="" asp-controller="Saida" asp-action="Create">Saídas</a>
                                </nav>
                            </div>
                            


                            <a class="nav-link" asp-area="" asp-controller="Grafico" asp-action="Index" asp-route-dias="360">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Gráficos
                            </a>
                           
                        <a class="nav-link " asp-area="" asp-controller="Relatorio" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-file"></i></div>
                            Relatórios
                            
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tabelas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                             
                                
                                   
                                        <a class="nav-link" asp-area="" asp-controller="Mercadoria" asp-action="List">Mercadorias</a>
                                        <a class="nav-link" asp-area="" asp-controller="Entrada" asp-action="List">Entradas</a>
                                        <a class="nav-link" asp-area="" asp-controller="Saida" asp-action="List">Saídas</a>
                                    
                             
                            </nav>
                        </div>
                    </div>
                     </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <div class="container-fluid p-0">
                     <main role="main" >
                        @RenderBody()
                     </main>
                </div>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    
    

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.1/chart.min.js" integrity="sha512-MC1YbhseV2uYKljGJb7icPOjzF2k6mihfApPyPhEAo3NsLUW0bpgtL4xYWK1B+1OuSrUkfOTfhxrRKCz/Jp3rQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>